### ISSUE TITLE
runtime error with latex

### ISSUE THREAD

**Issue by webbjosh** [RuthCoronaMoreno/COVID-19#1]
Hi! I'm having a runtime error  `RuntimeError: Failed to process string with tex because latex could not be found` when plotting the graphs. I already tried installing MacTex from [here](https://www.latex-project.org/get/) and searched everywhere how to fix the error I'm getting. Is there any other way to plot the figures with out using latex?

Thank you for any help that you may provide.
Josh

**Comment by RuthCoronaMoreno** [comment]
Hi!

Latex is just needed when you add a math symbol in a label of a plot. Maybe
there is an underscore in some of them. If it is the case remove the
underscore. But if you remove "labels" in plots, the code must be run and
it will add an standardized label for each graph in the plot.

I hope it can help you.

Thanks to write.

Ruth

**Comment by webbjosh** [comment]
I tried running your code as is and the error still persists. I am using both jupyter notebook in anaconda and google colab to run the code.

Josh

**Comment by webbjosh** [comment]
Hi! I already sorted it out. I just had to turn off/remove the usetex line from PDEparams.py.

Thank you so much!
